services:
  postgres:
    image: postgres:16-alpine
    container_name: fraud-db
    environment:
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_pass_dev
      POSTGRES_DB: fraud_detection
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud_user -d fraud_detection"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata: